deployment:
  toSsh:
    enabled: false
    host: "192.168.56.13"
    port: 22
    username: "stefanwalther"
    password: "Test1234"
    dest: "/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Extensions/sense-components"
  toLocal:
    enabled: false
    pathFetching: false
    localExtensionsBaseDir: ""
    extensionDirOverride: ""
import:
  fromSsh:
    enabled: false
    host: "192.168.56.13"
    port: 22
    username: "stefanwalther"
    password: "Test1234"
    files:
      - src: "/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Apps/Test-App.qvf"
        dest: "./examples/sense-components-samples"
shell:
  enabled: false
  tasks:
  - "rsync -ssh --delete -rtuv stefanwalther@192.168.56.13:/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Extensions/sense-components-samples ~/git/stefanwalther/sense-components/examples"
  - "rsync -ssh --delete -rtuv stefanwalther@192.168.56.13:/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Extensions/components ~/git/stefanwalther/sense-components/examples"
