sudo: true
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "node"
  - "iojs"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.10"
script: node_modules/karma/bin/karma start test/karma.conf.js --single-run
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
